{include file="sections/header.tpl"}
<style>
    /* Styles for overall layout and responsiveness */
    body {
        background-color: #f8f9fa;
        font-family: 'Arial', sans-serif;
        padding: 0;
        margin: 0;
    }

    .container {
        margin-top: 20px;
        background-color: #d8dfe5;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        padding: 20px;
        max-width: 98%;
        overflow-x: auto;
        flex-wrap: wrap;
        justify-content: space-between;
        align-items: center;
    }

    /* Styles for table and pagination */
    .table {
        width: 100%;
        margin-bottom: 1rem;
        background-color: #fff;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .table th {
        vertical-align: middle;
        border-color: #dee2e6;
        background-color: #343a40;
        color: #fff;
    }

    .table td {
        vertical-align: middle;
        border-color: #dee2e6;
    }

    .table-striped tbody tr:nth-of-type(odd) {
        background-color: rgba(0, 0, 0, 0.05);
    }

    .table-hover tbody tr:hover {
        background-color: rgba(0, 0, 0, 0.075);
        color: #333;
        font-weight: bold;
        transition: background-color 0.3s, color 0.3s;
    }

    .pagination .page-item .page-link {
        color: #007bff;
        background-color: #fff;
        border: 1px solid #dee2e6;
        margin: 0 2px;
        padding: 6px 12px;
        transition: background-color 0.3s, color 0.3s;
    }

    .pagination .page-item .page-link:hover {
        background-color: #e9ecef;
        color: #0056b3;
    }

    .pagination .page-item.active .page-link {
        z-index: 1;
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button {
        display: inline-block;
        padding: 5px 10px;
        margin-right: 5px;
        border: 1px solid #ccc;
        background-color: #fff;
        color: #333;
        cursor: pointer;
    }
</style>


<!-- <div class="btn-group pull-left">
    <button class="btn btn-success btn-xs" data-toggle="modal" data-target="#settings" title="General Settings"><span
         class="glyphicon glyphicon-cog" aria-hidden="true"></span> {Lang::T('Settings')}</button>
</div> -->
<!-- card -->
<div class="row" style="padding: 5px">
    <div class="col-lg-3 col-lg-offset-9">
        <div class="btn-group btn-group-justified" role="group">
            <div class="btn-group" role="group">
                <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#create"><i
                        class="ion ion-android-add"></i>
                    {Lang::T('Generate Cards')}</a>
            </div>
            <div class="btn-group" role="group">
                <a href="{$_url}plugin/recharge_cardsPrint" target="print_card" class="btn btn-info"><i
                        class="ion ion-android-print"></i> {Lang::T('Print All')}</a>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-hovered mb20 panel-primary">
    <div class="panel-heading">
        <!-- {if in_array($_admin['user_type'],['SuperAdmin','Admin'])}
        <div class="btn-group pull-right">
            <a class="btn btn-danger btn-xs" title="Remove used card" href="{$_url}plugin/hotspot_card"
                onclick="return confirm('Delete all used card code?')"><span class="glyphicon glyphicon-trash"
                    aria-hidden="true"></span> Delete All</a>
        </div>
        {/if} -->
        &nbsp;
    </div>


    <div class="container">
        <table id="datatable" class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <th><input type="checkbox" id="select-all"></th>
                    <th>{Lang::T('Card PIN')}</th>
                    <th>{Lang::T('Card Price')}</th>
                    <th>{Lang::T('Card Status')}</th>
                    <th>{Lang::T('Card Serial No')}</th>
                    <th>{Lang::T('Created Date')}</th>
                    <th>{Lang::T('Generated By')}</th>
                    <th>{Lang::T('Used Date')}</th>
                    <th>{Lang::T('Used By')}</th>
                    <th>{Lang::T('Manage')}</th>
                </tr>
            </thead>
            <tbody>
                {foreach $cards as $card}
                <tr>
                    <td><input type="checkbox" name="card_ids[]" value="{$card['id']}"></td>
                    <td style="background-color: black; color: black;"
                        onmouseleave="this.style.backgroundColor = 'black';"
                        onmouseenter="this.style.backgroundColor = 'white';">
                        {$card['card_number']}
                    </td>
                    <td>{$card['value']}</td>
                    <td>
                        {if $card['status'] == 'used'}
                        <span class="label label-danger">{Lang::T('Used')}</span>
                        {else}
                        <span class="label label-success">{Lang::T('Not Used')}</span>
                        {/if}
                    </td>
                    <td style="background-color: black; color: black;"
                        onmouseleave="this.style.backgroundColor = 'black';"
                        onmouseenter="this.style.backgroundColor = 'white';">
                        {$card['serial_number']}
                    </td>
                    <td>{$card['created_at']}</td>
                    <td>{if $card['admin_name']}
                        <a href="{$_url}settings/users-view/{$card['generated_by']}">{$card['admin_name']}</a>
                        {else} -
                        {/if}
                    </td>
                    <td>{$card['used_at']}</td>
                    <td>{if $card['used_by'] == '0'}
                        {Lang::T('None')}
                        {else}
                        <a href="{$_url}customers/view/{$card['customer_id']}">{$card['customer_name']}</a>
                    </td>
                    {/if}
                    <td>
                        {if $card['status'] neq 'used'}
                        <a href="{$_url}plugin/recharge_cards_print&card_id={$card['id']}" id="{$card['id']}"
                            style="margin: 0px;"
                            class="btn btn-success btn-xs">&nbsp;&nbsp;{Lang::T('Print')}&nbsp;&nbsp;</a>
                        {/if}
                        <button type="button" class="btn btn-primary btn-xs send-card" data-id="{$card['id']}"
                            data-toggle="modal" data-target="#sendCardModal">
                            <i class="glyphicon glyphicon-send"></i> {Lang::T('Send')}
                        </button>
                    </td>
                </tr>
                {/foreach}
            </tbody>
        </table>
        <br>
        <div class="row" style="padding: 5px">
            <div class="col-lg-3 col-lg-offset-9">
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        {if in_array($_admin['user_type'],['SuperAdmin','Admin'])}
                        <button id="deleteSelectedCards" class="btn btn-danger">{Lang::T('Delete
                            Selected')}</button>
                        {/if}
                    </div>
                    <div class="btn-group" role="group">
                        <button id="printSelectedCards" class="btn btn-success">{Lang::T('Print
                            Selected')}</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    &nbsp;

</div>

<div class="modal fade" id="settings">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"> {Lang::T('Generate Settings')}</h4>
            </div>
            <div class="box-body">
                <div class="tab-pane">
                    <form class="form-horizontal" method="post" autocomplete="off" role="form" action="">
                        <div class="form-group">
                            <label class="col-md-2 control-label">{Lang::T('Enable Recharge')}</label>
                            <div class="col-md-6">
                                <label class="switch">
                                    <input type="checkbox" id="recharge_cards_mode" value="1"
                                        name="recharge_cards_mode" {if $_c['recharge_cards_mode']==1}checked{/if}>
                                    <span class="slider"></span>
                                </label>
                            </div>
                        </div>
                        <div class="form-group" id="recharge-type-group">
                            <label class="col-md-2 control-label">{Lang::T('Recharge Notification')}</label>
                            <div class="col-md-6">
                                <select class="form-control" name="recharge_cards_notify" id="recharge_cards_notify">
                                    <option value="1" {if $_c['recharge_cards_notify']=='1' }selected{/if}>
                                        {Lang::T('Enabled')}</option>
                                    <option value="0" {if $_c['recharge_cards_notify']=='0' }selected{/if}>
                                        {Lang::T('Disabled')}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">{Lang::T('Enable Message')}</label>
                            <div class="col-md-6">
                                <label class="switch">
                                    <input type="checkbox" id="recharge_message" value="1" name="recharge_message" {if
                                        $_c['recharge_message']==1 }checked{/if}>
                                    <span class="slider"></span>
                                </label>
                            </div>
                        </div>
                        <div class="form-group" id="message-group">
                            <label class="col-md-2 control-label">{Lang::T('Send Via')}</label>
                            <div class="col-md-6">
                                <select class="form-control" name="recharge_message_via" id="recharge_message_via">
                                    <option value="sms" {if $_c['recharge']=='sms' }selected{/if}>
                                        {Lang::T('SMS')}</option>
                                    <option value="wa" {if $_c['recharge_message_via']=='wa' }selected{/if}>
                                        {Lang::T('WhatsApp')}</option>
                                    <option value="both" {if $_c['recharge_message_via']=='both' }selected{/if}>
                                        {Lang::T('Both')}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group" id="message-content-group">
                            <label class="col-md-2 control-label">{Lang::T('Message')}</label>
                            <div class="col-md-6">
                                <textarea class="form-control" id="recharge_message_content"
                                    name="recharge_message_content"
                                    rows="6">{Lang::htmlspecialchars($_json[''])}</textarea>
                            </div>
                            <p class="help-block col-md-4">
                                <b>[[login_code]]</b> - {Lang::T('will replace customer login code')}.<br>
                                <b>[[package]]</b> - {Lang::T('will replace customer package name')}.<br>
                                <b>[[expiry]]</b> - {Lang::T('will replace customer package expiry date')}.<br>
                                <b>[[company]]</b> - {Lang::T('will replace your Company Name')}.<br>
                            </p>
                        </div>
                        <div class="form-group" id="">
                            <label class="col-md-2 control-label">{Lang::T('Recharge  Send Template')}</label>
                            <div class="col-md-6">
                                <textarea rows="8" name="recharge_send" id="recharge_send"
                                    class="form-control">{Lang::htmlspecialchars($_json[''])}</textarea>
                            </div>
                            <p class="help-block col-md-4">
                                <b>[[code]]</b> - {Lang::T('will replace recharge code')}.<br>
                                <b>[[data]]</b> - {Lang::T('will replace recharge data limit')}.<br>
                                <b>[[validity]]</b> - {Lang::T('will replace recharge validity or duration')}.<br>
                                <b>[[company]]</b> - {Lang::T('will replace your Company Name')}.<br>
                            </p>
                        </div>

                        <div class="form-group" id="">
                            <label class="col-md-2 control-label">{Lang::T('Recharge Cards Print Template')}</label>
                            <div class="col-md-6">
                                <textarea rows="8" name="" id=""
                                    class="form-control">{Lang::htmlspecialchars($_json[''])}</textarea>
                            </div>
                            <p class="help-block col-md-4">
                                <b>[[currency]]</b> - {Lang::T('will replace recharge currency code')}.<br>
                                <b>[[plan_price]]</b> - {Lang::T('will replace recharge plan price')}.<br>
                                <b>[[code]]</b> - {Lang::T('will replace recharge code')}.<br>
                                <b>[[data]]</b> - {Lang::T('will replace recharge data limit')}.<br>
                                <b>[[validity]]</b> - {Lang::T('will replace recharge validity or duration')}.<br>
                                <b>[[url]]</b> - {Lang::T('will replace recharge with recharge login url')}.<br>
                                <b>[[qrcode]]</b> - {Lang::T('will replace recharge QRcode')}.<br>
                            </p>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <button class="btn btn-success btn-block" name="save" value="save" type="submit">
                                    {Lang::T('Save Changes')}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="panel panel-hovered mb20 panel-primary">
    <div class="panel-heading">
        {Lang::T('Locked Out Customers')}
        &nbsp;
    </div>

    <div class="container">
        <table id="locktable" class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <!-- <th><input type="checkbox" id="select-all"></th> -->
                    <th>{Lang::T('Customer Name')}</th>
                    <th>{Lang::T('Failed Attempts')}</th>
                    <th>{Lang::T('Last Attempt')}</th>
                    <th>{Lang::T('Locked Until')}</th>
                    <th>{Lang::T('Manage')}</th>
                </tr>
            </thead>
            <tbody>
                {foreach $lockouts as $lock}
                <tr>
                    <!-- <td><input type="checkbox" name="lock_ids[]" value="{$lock['id']}"></td> -->
                    <td><a href="{$_url}customers/view/{$lock['user_id']}">{$lock['customer_name']}</a></td>
                    <td>
                        {if $lock['failed_attempts'] >= '5'}
                        <span class="label label-danger">{Lang::T('Locked Out')}</span>
                        {else}
                        <span class="label label-warning">{$lock['failed_attempts']}</span>
                        {/if}
                    </td>
                    <td>{$lock['last_attempt']}</td>
                    <td>{$lock['locked_until']}</td>

                    <td>
                        <a href="{$_url}plugin/recharge_cardsUnblock&id={$lock['user_id']}" id="{$lock['user_id']}"
                            onclick="return confirm('{Lang::T(" Are You Sure?")}')" style="margin: 0px;"
                            class="btn btn-success btn-xs">{Lang::T('Unlock')}</a>
                    </td>
                </tr>
                {/foreach}
            </tbody>
        </table>
        <br>
    </div>
    &nbsp;

</div>

<form id="printSelectedForm" method="POST" action="{$_url}plugin/recharge_cards_print">
    <input type="hidden" name="cardIds" id="cardIdsInput">
</form>

<div class="modal fade" id="create">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"> {Lang::T('Generate Cards')}</h4>
            </div>
            <div class="box-body">
                <div class="tab-pane">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <div class="form-group">
                            <label for="inputExperience" class="col-sm-2 control-label">{Lang::T('No of
                                Cards')}</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="number_of_cards" value="1">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputSkills" class="col-sm-2 control-label">
                                {Lang::T('PIN Length')}</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="lengthcode" value="12">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputSkills" class="col-sm-2 control-label">
                                {Lang::T('Card Value')}</label>
                            <div class="col-sm-10">
                                <input type="card_value" class="form-control" name="card_value"
                                    placeholder="Recharge Amount" value="">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputSkills" class="col-sm-2 control-label"> {Lang::T('Print
                                Now')}</label>

                            <div class="col-sm-10">
                                <input type="checkbox" id="print_now" name="print_now" class="iCheck" value="1">
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="pull-right">
                                <button type="submit" value="Generate " class="btn btn-primary">
                                    <i class="fa fa-telegram">
                                    </i> {Lang::T('Generate')}</button>
                            </div>
                            <button type="button" data-dismiss="modal" class="btn btn-danger">
                                <i class="">
                                </i> {Lang::T('Cancel')}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




<!-- Send Card Modal HTML -->

<div class="modal fade" id="sendCardModal" tabindex="-1" role="dialog" aria-labelledby="sendCardLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="sendCardLabel"> {Lang::T('Send Card PIN')}</h4>
            </div>
            <div class="box-body">
                <div class="tab-pane">
                    <form action="{$_url}plugin/recharge_cards_sendCard" method="post" enctype="multipart/form-data"
                        class="form-horizontal">
                        <input type="hidden" id="cardId" name="cardId">
                        <div class="form-group">
                            <label for="phone_number" class="col-sm-2 control-label">{Lang::T('Phone No')}</label>
                            <div class="col-sm-10">
                                <input type="text" id="phone_number" name="phoneNumber"
                                    placeholder="{Lang::T('Enter the receiver phone number')}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="method" class="col-sm-2 control-label">{Lang::T('Send Via')}</label>
                            <div class="col-sm-10">
                                <select name="method" id="method" class="form-control">
                                    <option value="sms">{Lang::T('SMS')}</option>
                                    <option value="wa">{Lang::T('WhatsApp')}</option>
                                    <option value="both">{Lang::T('Both')}</option>
                                </select>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="pull-right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-telegram"></i> {Lang::T('Send Now')}
                                </button>
                            </div>
                            <button type="button" data-dismiss="modal" class="btn btn-danger">
                                <i class=""></i> {Lang::T('Cancel')}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
<script>
    // Select or deselect all checkboxes
    document.getElementById('select-all').addEventListener('change', function () {
        var checkboxes = document.querySelectorAll('input[name="card_ids[]"]');
        for (var checkbox of checkboxes) {
            checkbox.checked = this.checked;
        }
    });

    // Handle delete selected Cards
    document.getElementById('deleteSelectedCards').addEventListener('click', function () {
        var selectedCards = [];
        document.querySelectorAll('input[name="card_ids[]"]:checked').forEach(function (checkbox) {
            selectedCards.push(checkbox.value);
        });

        if (selectedCards.length > 0) {
            if (confirm('Are you sure you want to delete the selected cards?')) {
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '{$_url}plugin/recharge_cards_delete', true);
                xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                xhr.onload = function () {
                    if (xhr.status === 200) {
                        location.reload(); // Reload the page to reflect the changes
                    } else {
                        console.error('Failed to delete cards: ', xhr.responseText);
                    }
                };
                xhr.send('cardIds=' + JSON.stringify(selectedCards));
            }
        } else {
            alert('Please select at least one card to delete.');
        }
    });

    // Handle single card deletion
    document.querySelectorAll('.delete-card').forEach(function (button) {
        button.addEventListener('click', function () {
            var cardId = this.getAttribute('data-id');
            if (confirm('Are you sure you want to delete this card?')) {
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '{$_url}plugin/recharge_cards_delete', true);
                xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                xhr.onload = function () {
                    if (xhr.status === 200) {
                        location.reload(); // Reload the page to reflect the changes
                    } else {
                        console.error('Failed to delete card: ', xhr.responseText);
                    }
                };
                xhr.send('cardIds=' + JSON.stringify([cardId]));
            }
        });
    });
</script>
<script>
    const $q = jQuery.noConflict();

    $q(document).ready(function () {
        $q('#locktable').DataTable({
            "pagingType": "full_numbers",
            "order": [
                [1, 'desc']
            ]
        });
    });
</script>
<script>
    const $j = jQuery.noConflict();

    $j(document).ready(function () {
        $j('#datatable').DataTable({
            "pagingType": "full_numbers",
            "order": [
                [1, 'desc']
            ]
        });
    });
</script>
<script>
    document.getElementById('printSelectedCards').addEventListener('click', function () {
        var selectedCards = [];
        document.querySelectorAll('input[name="card_ids[]"]:checked').forEach(function (checkbox) {
            selectedCards.push(checkbox.value);
        });

        if (selectedCards.length > 0) {
            document.getElementById('cardIdsInput').value = JSON.stringify(selectedCards);
            document.getElementById('printSelectedForm').submit();
        } else {
            alert('Please select at least one card to print.');
        }
    });
</script>
<script>
    var $ = jQuery.noConflict();
    $(document).ready(function () {
        $('.send-card').on('click', function () {
            var cardId = $(this).data('id');
            console.log('card ID:', cardId);
            $('#sendCardModal').find('#cardId').val(cardId); // Corrected ID reference
        });
    });
</script>



{include file="sections/footer.tpl"}